### ISSUE TITLE
Trusted device

### ISSUE THREAD

**Issue by jwilk** [jwilk/mbank-cli#74]
Some users want mbank-cli to register as a trusted "device".

**Comment by jwilk** [comment]
As @MrDefacto noted in <https://github.com/bgaluszka/mbank/issues/18#issuecomment-531602257>, the cookie `mBank8` is used for identifying the device. Indeed, in my tests in web the browser, having the right `mBank8` cookie seems to be necessary and sufficient to skip SMS auth.

However, I didn't have any success with transplanting the browser's cookie to mbank-cli's cookie jar. I'm still getting SMS auth request. I don't know what's going on. :-(

**Comment by chilek** [comment]
> However, I didn't have any success with transplanting the browser's cookie to mbank-cli's cookie jar. I'm still getting SMS auth request. I don't know what's going on. :-(

It's quite possible that this cookie contains encrypted information about your browser details and when you use it from the other web browser (mbank-cli is kind of web client) web browser properties mismatch with those contained in cookie. Try to set user agent the same as in earlier used web browser. If they use advanced web browser fingerprinting it doesn't resolve the problem as other web client attributes can be checked.

**Comment by jwilk** [comment]
Setting the same User-Agent doesn't help. ☹

**Comment by chilek** [comment]
I called to mLinia and they said that they had serious problems with trusted device feature and they are working to resolve these problem. They plan to add trusted device management in their webui.

**Comment by KptChaos** [comment]
Just a little bit OT. Guys. I really don't know if I should cry or laugh. All banks knew months before, that they will have to make some small changes in loging procedure... It looks like they didn't prepare for it good enough. Bug after bug. Looking from my perpective it looks like they didn't even TESTED their systems before launch! Why? I used token card in mBank. I didn't swap it for sms auth before changes. Yesterday I've tried to log in to mBank. And you know what was their system reaction? UNKNOWN ERROR, and forced log out!!! No info - "dear client, sorry but you can't log in, since we don't have your phone number or you didn't change auth method bla bla bla" no, some "magical" error, and forced log out. Really? Could this situation be so "unpredictable", hard to "forsee" that NO ONE couldn't code it properly? Another good example - Alior Bank. Today I've tried to log in. I used transaction auth via sms code for a long time so I was 100% sure I won't have any kind of issue with log in. Well, I was wrong. I entered password, username and then... input field poped up for SMS code. That's ok... but I didn't get any kind of SMS, nor immediately nor 4 hours after... I wrote email to support and they replied with a lot of bullshit, along with something like "maybe you didn't set trusted phone number" I said ok, maybe, BUT WHY THE FUCK system DIDN"T informed me about this, instead -"sent" SMS to... well who know where and waited for my code? Why we, customers have to play detectives or beta testers?

**Comment by jwilk** [comment]
The missing secret sauce is the `DfpData` thing (which is indeed some kind of browser fingerprint) in the `JsonLogin` request.

After transplanting DFP from the browser to mbank-cli, I was able to log in without SMS password.

**Comment by jwilk** [comment]
I've pushed my preliminary code as d8576440720e0d9b6f4d57885f118e7797479e61 (`pu/74` branch).

You can now set custom DFP in the configuration file.
To get your browser's DFP, run this in the web console:
```js
Ebre.Behaviour.GetCurrentDfp()._rejectionHandler0
```

Logging in doesn't quite work yet, because you'll get:
```
Scraping error: login.redirect-url: /pl at ./mbank-cli line 1188.
```
Pretend that you didn't see the error message. ☺
(I'll fix the error after some refactoring. This function is now way too complex…)

Beware that at the moment the `logout` command wipes all cookies, including the crucial `mBank8`.

**Comment by chilek** [comment]
DFP = Digital FingerPrint?

**Comment by jwilk** [comment]
> ```
> Scraping error: login.redirect-url: /pl at ./mbank-cli line 1188.
> ```

I've fixed that and merged the feature to master (because why not).
Enjoy your transplantations. ☺

**Comment by chilek** [comment]
I called to mLinia again, because I am still not able to add my Google Chrome to trusted devices.
Although popup shows me that possibily -  after confirm I get "Już wcześniej dodałeś to urządzenie do zaufanych.". Trully I've added this Google Chrome earlier, but then I've deleted all cookie for online.mbank.pl domain. They created ticket in their system to resolve this problem.
Why am I writing this? Because this points that the cookie is not the only method of trusted devices. mBank has also them in its server database.

**Comment by b44x** [comment]
@chilek - They using browser "fingerprint", not cookie.

**Comment by chilek** [comment]
@b44x are you sure. As far is I Know @jwilk implemented batch logging (without SMS and mobile app) using cookies taken from desktop web browser. Quite possible that generated DFP is also stored in mBank database, but cookies are still used.

**Comment by jwilk** [comment]
> Beware that at the moment the `logout` command wipes all cookies, including the crucial `mBank8`.

I've fixed that in df708917740bdb1ce440e536062e93b935c77686.

**Comment by jwilk** [comment]
In b9dfb0e275ba7d9d4699880a11278c1be78c3dd2 (branch `pu/74`), I've added the command `register-device`.
Please give it a try!
(If you had played with transplanting cookies etc., please remove cookies from the cookie jar and the DFP directive from the config file before running the command.)

**Comment by jwilk** [comment]
I've documentation in 8a14d2a42c464ed0636f020c7ea53ad963f2d038.

**Comment by jwilk** [comment]
BTW, I don't quite like the name on the new command, so if you have better ideas, please speak up. ☺

**Comment by chilek** [comment]
For me register-device works as it should.

**Comment by chilek** [comment]
> BTW, I don't quite like the name on the new command, so if you have better ideas, please speak up. ☺

Yes - I have better idea: `zarejestruj-urządzenie' :D

**Comment by jwilk** [comment]
Yay, thanks for testing.
Merged to master as 70bbf58da2490f558862a3c6012338d99a5eccf0.
I hope to make a new release on Monday.

**Comment by jwilk** [comment]
Fixed in [mbank-cli 2.2](https://github.com/jwilk/mbank-cli/releases/tag/2.2).
